name: flutter_app
description: A Flutter app for listing VVS publications
publish_to: "none"

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  html_unescape: ^2.0.0
  http: ^1.2.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3

  connectivity_plus: ^7.0.0

  openid_client: ^0.4.7
  url_launcher: ^6.2.5

flutter:
  uses-material-design: true
  assets:
    - assets/publications.json
